import { z } from "zod/v4";

/** Insight types produced by the Watcher's detector pipeline */
export type InsightType =
  | "unused_subscription"
  | "bill_increase"
  | "trial_expiration"
  | "lifestyle_inflation"
  | "anomalous_transaction"
  | "cost_creep"
  | "recurring_charge"
  | "behavioral_pattern"
  | "forgotten_trial"
  | "overdraft_prediction";

/** Urgency levels — immediate insights bypass notification batching */
export type InsightUrgency = "immediate" | "batched";

/** An insight generated by a Watcher detector */
export interface Insight {
  readonly type: InsightType;
  readonly urgency: InsightUrgency;
  readonly merchantName?: string;
  /** Decimal string — monetary amount related to the insight */
  readonly amount?: string;
  readonly description: string;
  readonly metadata: Record<string, unknown>;
  readonly detectedAt: string;
}

/** Overdraft prediction with 20% safety buffer applied */
export interface OverdraftPrediction {
  readonly predictedDate: string;
  /** Decimal string — projected shortfall amount */
  readonly projectedShortfall: string;
  /** Decimal string — current account balance */
  readonly currentBalance: string;
  /** Decimal string — projected expenses with 20% buffer */
  readonly projectedExpenses: string;
  readonly suggestedActions: string[];
  readonly confidence: number;
}

/** A transaction after categorization by the two-pass pipeline */
export interface CategorizedTransaction {
  readonly transactionId: string;
  readonly merchantName: string;
  readonly merchantCategory: string;
  readonly categoryRuleMatched?: string;
  readonly categoryConfidence: number;
  /** Decimal string — transaction amount */
  readonly amount: string;
  readonly transactionDate: string;
}

/** Recurring charge frequency */
export type RecurringFrequency =
  | "weekly"
  | "biweekly"
  | "monthly"
  | "quarterly"
  | "annual";

/** Recurring charge status */
export type RecurringChargeStatus = "active" | "unused" | "cancelled" | "paused";

/** A detected recurring charge pattern */
export interface RecurringCharge {
  readonly id: string;
  readonly merchantName: string;
  /** Decimal string — current charge amount */
  readonly amount: string;
  /** Decimal string — previous charge amount (for increase detection) */
  readonly previousAmount?: string;
  readonly frequency: RecurringFrequency;
  readonly nextExpectedDate?: string;
  readonly lastChargedDate?: string;
  readonly lastUsageDate?: string;
  readonly daysSinceUsage?: number;
  readonly isTrial: boolean;
  readonly trialEndDate?: string;
  readonly status: RecurringChargeStatus;
}


/** A ghost action — simulated action shown in Phase 1 to demonstrate value */
export interface GhostAction {
  readonly id: string;
  readonly userId: string;
  readonly insightType: InsightType;
  readonly description: string;
  /** Decimal string — estimated savings if the action were executed */
  readonly estimatedSavings: string;
  readonly targetMerchant?: string;
  readonly createdAt: string;
}

/** Context passed to each detector in the pipeline */
export interface DetectorContext {
  readonly userId: string;
  readonly currentDate: string;
  readonly locale: string;
}

/** Detector interface — each of the 9 detector types implements this */
export interface Detector {
  readonly name: string;
  detect(
    userId: string,
    txs: ReadonlyArray<CategorizedTransaction>,
    ctx: DetectorContext,
  ): Promise<Insight[]>;
}

/** Zod schema for Insight validation */
export const InsightSchema = z.object({
  type: z.enum([
    "unused_subscription",
    "bill_increase",
    "trial_expiration",
    "lifestyle_inflation",
    "anomalous_transaction",
    "cost_creep",
    "recurring_charge",
    "behavioral_pattern",
    "forgotten_trial",
    "overdraft_prediction",
  ]),
  urgency: z.enum(["immediate", "batched"]),
  merchantName: z.string().optional(),
  amount: z.string().optional(),
  description: z.string().min(1),
  metadata: z.record(z.string(), z.unknown()),
  detectedAt: z.iso.datetime(),
});

/** Zod schema for OverdraftPrediction validation */
export const OverdraftPredictionSchema = z.object({
  predictedDate: z.string().min(1),
  projectedShortfall: z.string().min(1),
  currentBalance: z.string().min(1),
  projectedExpenses: z.string().min(1),
  suggestedActions: z.array(z.string()),
  confidence: z.number().min(0).max(1),
});
